---
# Tasks for Debian
- block:
  - name: Getting DEB architecture
    ansible.builtin.shell:
      cmd: dpkg --print-architecture
    register: deb_architecture
  - name: Updating the guest operating system.
    ansible.builtin.apt:
      update_cache: true
  - name: Installing additional packages
    ansible.builtin.apt:
      force_apt_get: true
      name: '{{ item }}'
    with_items:
      - bash-completion
      - curl
      - ca-certificates
      - gnupg
      - wget
      - git
      - net-tools
      - unzip
      - vim
      - make
      - build-essential
      - libssl-dev
    become: true
  - name: Uninstalling conflicting docker packages
    ansible.builtin.apt:
      name:
        - docker.io
        - docker-doc
        - docker-compose
        - podman-docker
        - containerd
        - runc
      state: absent
  - name: Creating gpg keyring
    ansible.builtin.shell:
      cmd: sudo install -m 0755 -d /etc/apt/keyrings
  - name: Getting docker.io GPG key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/debian/gpg
      keyring: /etc/apt/keyrings/docker.gpg
  - name: Adding docker.io apt repository
    ansible.builtin.apt_repository:
      repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
      filename: docker
      state: present
      update_cache: true
  - name: Installing docker
    ansible.builtin.apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      update_cache: true
  - name: Running cloud init clean
    ansible.builtin.shell:
      cmd: |
        sudo cloud-init clean && sudo sync
  become: true