name: Packer Build

on:
   push:

permissions:
   actions: write
   checks: read
   contents: read

env:
  packer_version: 1.9.4

jobs:
  win-11-files:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        path:
          - ./builds/windows/desktop/11
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: list-files
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: ${{ matrix.path }}
          ext: .pkr.hcl
  win-11:
    runs-on: self-hosted
    needs: win-11-files
    env:
      build: win11
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    strategy:
      fail-fast: true
      matrix:
        build: ${{ fromJson(needs.win-11-files.outputs.paths) }}
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - name: git secret
        id: git-secret
        run: |
          echo "$GPG_PRIVATE_KEY" > ./private_key.gpg
          gpg --batch --yes --pinentry-mode loopback --import private_key.gpg
          git secret reveal -p "$GPG_PASSWORD"
          ls -la ${{ matrix.build }}
      - id: setup
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.packer_version }}
      - id: init
        run: |
          packer init ${{ matrix.build }}
