name: Packer Build

on:
  push:

env:
  PACKER_VERSION: "1.9.4"

jobs:
  list-files:
    runs-on: self-hosted
    strategy:
      matrix:
        build_path:
          - ./builds/linux/debian/12
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}

    steps:
      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: ${{ matrix.build_path }}
          ext: ".pkr.hcl"

  packer-build:
    needs: list-files
    runs-on: self-hosted
    strategy:
      matrix:
        paths: ${{ fromJson(needs.list-files.outputs.paths) }}    
    
    steps:
      #- name: Checkout
      #  uses: actions/checkout@v3
      
      - name: Setup packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PACKER_VERSION }}
      
      - name: Run `packer init`
        id: init
        run: packer init ${{ matrix.paths }}
      
      - name: Run `packer validate`
        id: validate
        run: | 
          packer validate \
            -var 'proxmox_url=${{ secrets.PROXMOX_URL }}' \
            -var 'proxmox_username=${{ secrets.PROXMOX_USERNAME }}' \
            -var 'proxmox_api_token=${{ secrets.PROXMOX_API_TOKEN_ID }}' \
            -var 'proxmox_api_token_id=${{ secrets.PROXMOX_API_TOKEN }}' \
            -var 'proxmox_node=${{ secrets.PROXMOX_NODE }}' \
            -var 'proxmox_resource_pool=${{ secrets.PROXMOX_RESOURCE_POOL }}' \
            -var 'vm_nic_vlan=${{ secrets.VLAN_ID }}' \
            -var 'vm_scsi_controller=virtio-scsi-single' \
            -var 'enable_cloud_init=true' \
            -var 'cloud_init_storage_pool=${{ secrets.CLOUD_INIT_STORAGE_POOL }}' \
            -var 'http_ip=${{ secrets.HTTP_IP }}' \
            -var 'build_username=${{ secrets.BUILD_USERNAME }}' \
            -var 'build_password=${{ secrets.BUILD_PASSWORD }}' \
            -var 'build_key=${{ secrets.BUILD_KEY }}' \
            -var 'ansible_username=${{ secrets.ANSIBLE_USERNAME }}' \
            -var 'ansible_password=${{ secrets.ANSIBLE_PASSWORD }}' \
            -var 'ansible_key=${{ secrets.ANSIBLE_KEY }}' \
            ${{ matrix.paths }}
      
      - name: Run `packer build`
        id: build
        run: | 
          packer build \
          -var 'proxmox_url=${{ secrets.PROXMOX_URL }}' \
          -var 'proxmox_username=${{ secrets.PROXMOX_USERNAME }}' \
          -var 'proxmox_api_token=${{ secrets.PROXMOX_API_TOKEN_ID }}' \
          -var 'proxmox_api_token_id=${{ secrets.PROXMOX_API_TOKEN }}' \
          -var 'proxmox_node=${{ secrets.PROXMOX_NODE }}' \
          -var 'proxmox_resource_pool=${{ secrets.PROXMOX_RESOURCE_POOL }}' \
          -var 'vm_nic_vlan=${{ secrets.VLAN_ID }}' \
          -var 'vm_scsi_controller=virtio-scsi-single' \
          -var 'enable_cloud_init=true' \
          -var 'cloud_init_storage_pool=${{ secrets.CLOUD_INIT_STORAGE_POOL }}' \
          -var 'http_ip=${{ secrets.HTTP_IP }}' \
          -var 'build_username=${{ secrets.BUILD_USERNAME }}' \
          -var 'build_password=${{ secrets.BUILD_PASSWORD }}' \
          -var 'build_key=${{ secrets.BUILD_KEY }}' \
          -var 'ansible_username=${{ secrets.ANSIBLE_USERNAME }}' \
          -var 'ansible_password=${{ secrets.ANSIBLE_PASSWORD }}' \
          -var 'ansible_key=${{ secrets.ANSIBLE_KEY }}' \
          ${{ matrix.paths }}            


  

