name: Packer Validate and Format

on:
  push:

env:
  PACKER_VERSION: "1.9.4"
  PROXMOX_URL: ${{ secrets.PROXMOX_URL }}
  PROXMOX_USERNAME: ${{ secrets.PROXMOX_USERNAME }}
  PROXMOX_API_TOKEN_ID: ${{ secrets.PROXMOX_API_TOKEN_ID }}
  PROXMOX_API_TOKEN: ${{ secrets.PROXMOX_API_TOKEN }}
  PROXMOX_NODE: ${{ secrets.PROXMOX_NODE }}
  PROXMOX_RESOURCE_POOL: ${{ secrets.PROXMOX_RESOURCE_POOL }}
  CLOUD_INIT_STORAGE_POOL: ${{ secrets.CLOUD_INIT_STORAGE_POOL }}
  BUILD_USERNAME: ${{ secrets.BUILD_USERNAME }}
  BUILD_PASSWORD: ${{ secrets.BUILD_PASSWORD }}
  BUILD_KEY: ${{ secrets.BUILD_KEY }}
  ANSIBLE_USERNAME: ${{ secrets.ANSIBLE_USERNAME }}
  ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
  ANSIBLE_KEY: ${{ secrets.ANSIBLE_KEY }}
  HTTP_IP: ${{ secrets.HTTP_IP }}

jobs:
  list-files:
    runs-on: self-hosted
    strategy:
      matrix:
        build_path:
          - ./builds/linux/debian/12
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}

    steps:
      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: ${{ matrix.build_path }}
          ext: ".pkr.hcl"

  packer-lint:
    needs: list-files
    runs-on: self-hosted
    strategy:
      matrix:
        paths: ${{ fromJson(needs.list-files.outputs.paths) }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PACKER_VERSION }}
      
      - name: Run `packer init`
        id: init
        run: packer init ${{ matrix.paths }}
      
      - name: Run `packer fmt`
        id: fmt
        run: packer fmt ${{ matrix.paths }}



  

