name: Packer Validate and Format

on:
  push:

env:
  PACKER_VERSION: "1.9.4"


jobs:
  list-files:
    runs-on: self-hosted
    strategy:
      matrix:
        build_path:
          - ./builds/linux/debian/12
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}

    steps:
      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: ${{ matrix.build_path }}
          ext: ".pkr.hcl"

  packer-lint:
    needs: list-files
    runs-on: self-hosted
    strategy:
      matrix:
        paths: ${{ fromJson(needs.list-files.outputs.paths) }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PACKER_VERSION }}
      
      - name: Run `packer init`
        id: init
        run: packer init ${{ matrix.paths }}



  

