name: Packer Validate and Format

on:
  push:

env:
  PACKER_VERSION: "1.9.4"


jobs:
  list-files:
    runs-on: self-hosted
    strategy:
      matrix:
        build_path:
          - ./builds/linux/debian/12
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}

    steps:
      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: ${{ github.repository }}
          path: ${{ matrix.build_path }}
          ext: ".pkr.hcl"

  Test:
    needs: list-files
    runs-on: self-hosted
    strategy:
      matrix:
        paths: ${{ fromJson(needs.list-files.outputs.paths) }}
    
    steps:
      - name: Output results
        run: | 
          echo ${{ matrix.paths }}



  

